repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.3.5
    hooks:
      - id: go-fmt
        # pass_filenames: false
      - id: go-vet
        # pass_filenames: false
      - id: go-lint
        # pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        # pass_filenames: false
      - id: end-of-file-fixer
        # pass_filenames: false
