name: Go Lint CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Run golangci-lint on PR
        if: github.event_name == 'pull_request'
        uses: golangci/golangci-lint-action@v3
        with:
          args: --new-from-rev ${{ github.event.pull_request.base.sha }} --config .golangci.yaml
          version: latest

      - name: Run golangci-lint on main branch push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --config .golangci.yaml
